config/routes.rb
Rails.application.routes.draw do
  get 'formulas/index'
  get 'formulas/show'
  get 'formulas/edit'
  get 'formulas/new'
  resources :formulas

  get 'records/index'
  get 'records/show'
  get 'records/edit'
  get 'records/new'
  resources :records

  get 'models/index'
  get 'models/show'
  get 'models/edit'
  get 'models/new'
  resources :models

  get 'machines/index'
  get 'machines/show'
  get 'machines/edit'
  get 'machines/new'
  resources :machines

end

app/models/formula.rb
class Formula < ActiveRecord::Base
end

app/models/machine.rb
class Machine < ActiveRecord::Base
  
end

app/models/model.rb
class Model < ActiveRecord::Base
end

app/models/record.rb
class Record < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/formulas_controller.rb
class FormulasController < ApplicationController
  def index
    @formula = Formula.all
  end

  def show
    @formula = Formula.find(params[:id])
  end

  def new
    @formula = Formula.new
  end

  def create
    @formula = Formula.new(model_params)
    if @formula.save
      redirect_to '/formulas'
    else
      render 'new'
    end
  end

  def edit
    @formula = Formula.find(params[:id])
  end

  def update
    @formula = Formula.find(params[:id])
    if @formula.update_attributes(model_params)
      # 更新に成功したときの処理
      redirect_to '/formulas'
    else
      render 'edit'
    end
  end

  private
  def model_params
    params.require(:formula).permit(:model_id, :criteria, :big, :reg, :roll)
  end

end

app/controllers/machines_controller.rb
class MachinesController < ApplicationController
  def index
    @machine = Machine.all
  end

  def show
    @machine = Machine.find(params[:id])
  end

  def new
    @machine = Machine.new
  end

  def create
    @machine = Machine.new(model_params)
    if @machine.save
      redirect_to '/machines'
    else
      render 'new'
    end
  end

  def edit
    @machine = Machine.find(params[:id])
  end

  def update
    @machine = Machine.find(params[:id])
    if @machine.update_attributes(model_params)
      # 更新に成功したときの処理
      redirect_to '/machines'
    else
      render 'edit'
    end
  end

  private
  def model_params
    params.require(:machine).permit(:number, :model_id, :from, :to)
  end

end

app/controllers/models_controller.rb
class ModelsController < ApplicationController
  def index
    @model = Model.all
  end

  def show
    @model = Model.find(params[:id])
  end

  def new
    @model = Model.new
  end

  def create
    @model = Model.new(model_params)
    if @model.save
      redirect_to '/models'
    else
      render 'new'
    end
  end

  def edit
    @model = Model.find(params[:id])
  end

  def update
    @model = Model.find(params[:id])
    if @model.update_attributes(model_params)
      # 更新に成功したときの処理
      redirect_to '/models'
    else
      render 'edit'
    end
  end

  private
  def model_params
    params.require(:model).permit(:name)
  end

end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  def index
    if params[:sel_day].blank? then
      day = Time.now.strftime("%Y-%m-%d")
    else
      sel_day = params[:sel_day]
      day = sel_day['day']
    end
    @record = Record.where("date = :date" ,date: day)
    # @record = Record.all
  end

  def show
    @record = Record.find(params[:id])
  end

  def new
    @record = Record.new
  end

  def create
    @record = Record.new(model_params)

    machine = Machine.where("id = :id" , id: params[:machine_id])
    formula = Formula.where("model_id = :model_id" ,model_id: 1).order("criteria")

    formula.each do |f|
      get    = (@record.big * f.big + @record.reg * f.reg)
      rost   = (@record.roll / f.roll).floor * 50
      result = get - rost
      case f.criteria
      when 1 then
        @record.dry = result
      when 2 then
        @record.result = result
      when 3 then
        @record.sweet = result
      end
    end

    if @record.save
      redirect_to '/records'
    else
      render 'new'
    end
  end

  def edit
    @record = Record.find(params[:id])
  end

  def update
    @record = Record.find(params[:id])
    if @record.update_attributes(model_params)
      # 更新に成功したときの処理
      redirect_to '/records'
    else
      render 'edit'
    end
  end

  private
  def model_params
    params.require(:record).permit(:machine_id,:date,:big,:reg,:art,:roll,:final_roll,:sel_day)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/formulas_helper.rb
module FormulasHelper
end

app/helpers/machines_helper.rb
module MachinesHelper
end

app/helpers/models_helper.rb
module ModelsHelper
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/views/formulas/edit.html.erb
<h1>Formulas#edit</h1>
<p>Find me in app/views/formulas/edit.html.erb</p>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@formula) do |f| %>
      <%= f.label :model_id %>
      <%= f.text_field :model_id, class: 'form-control' %>
      <%= f.label :criteria %>
      <%= f.text_field :criteria, class: 'form-control' %>
      <%= f.label :big %>
      <%= f.text_field :big, class: 'form-control' %>
      <%= f.label :reg %>
      <%= f.text_field :reg, class: 'form-control' %>
      <%= f.label :roll %>
      <%= f.text_field :roll, class: 'form-control' %>
      <%= f.submit "変更", class: "btn btn-primary" %>
    <% end %>
</div>
<%= button_to "戻る", formulas_index_path ,method: :get %>

app/views/formulas/index.html.erb
<h1>Formulas#index</h1>

<table>
  <tr>
    <th width="20">No</th>
    <th width="200">機種名</th>
    <th width="200">基準</th>
    <th width="100">Big</th>
    <th width="100">Reg</th>
    <th width="100">回転数</th>
  </tr>
  <% i = 1 %>
  <% @formula.each do |m| -%>
  <tr>
    <td><a href="/formulas/<%= m.id %>"><%= i %></a></td>
    <td><%= m.model_id %></td>
    <td><%= m.criteria %></td>
    <td><%= m.big %></td>
    <td><%= m.reg %></td>
    <td><%= m.roll %></td>
    <td><a href="/formulas/<%= m.id %>">表示</a>
        <a href="/formulas/<%= m.id %>/edit">変更</a></td>
  </tr>
  <% i=i+1 %>
  <% end -%>
</table>
<%= button_to "新規作成", formulas_new_path ,method: :get %>

app/views/formulas/new.html.erb
<h1>Formulas#new</h1>
<p>Find me in app/views/formulas/new.html.erb</p>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@formula) do |f| %>
      <%= f.label "機種" %>
      <%= f.collection_select :model_id, Model.all, :id, :name,:prompt => "選択してください" %>
      <br>
      <%= f.label "基準" %>
      <%= f.select :criteria, {"辛口"=>"1","普通"=> "2", "甘口" => "3"},:prompt => "選択してください" %>
      <br>
      <%= f.label "Big枚数" %>
      <%= f.text_field :big, class: 'form-control' %>
      <br>
      <%= f.label "Reg枚数" %>
      <%= f.text_field :reg, class: 'form-control' %>
      <br>
      <%= f.label "回転数" %>
      <%= f.text_field :roll, class: 'form-control' %>
      <br>
      <%= f.submit "作成", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>
<%= button_to "戻る", formulas_index_path ,method: :get %>

app/views/formulas/show.html.erb
<h1>Formulas#show</h1>
<p>Find me in app/views/formulas/show.html.erb</p>

<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h3>ID:<%= @formula.id %></h3>
      <h3>機種名:<%= @formula.model_id %></h3>
      <h3>基準:<%= @formula.criteria %></h3>
      <h3>Big:<%= @formula.big %></h3>
      <h3>Reg:<%= @formula.reg %></h3>
      <h3>回転数:<%= @formula.roll %></h3>
    </section>
  </aside>
</div>
<%= button_to "戻る", formulas_index_path ,method: :get %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pro</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/machines/edit.html.erb
<h1>Machines#edit</h1>
<p>Find me in app/views/machines/edit.html.erb</p>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@machine) do |f| %>
      <%= f.label :number %>
      <%= f.text_field :number, class: 'form-control' %>
      <%= f.label :model_id %>
      <%= f.text_field :model_id, class: 'form-control' %>
      <%= f.label :from %>
      <%= f.text_field :from, class: 'form-control' %>
      <%= f.label :to %>
      <%= f.text_field :to, class: 'form-control' %>
      <%= f.submit "変更", class: "btn btn-primary" %>
    <% end %>
</div>
<%= button_to "戻る", machines_index_path ,method: :get %>

app/views/machines/index.html.erb
<h1>Machines#index</h1>
<p>Find me in app/views/machines/index.html.erb</p>

<table>
  <tr>
    <th width="20">No</th>
    <th width="120">台番号</th>
    <th width="200">機種名</th>
    <th width="200">期間開始</th>
    <th width="100">期間終了</th>
  </tr>
  <% i = 1 %>
  <% @machine.each do |m| -%>
  <tr>
    <td><a href="/machines/<%= m.id %>"><%= i %></a></td>
    <td><%= m.number %></td>
    <td><%= m.model_id %></td>
    <td><%= m.from %></td>
    <td><%= m.to %></td>
    <td><a href="/machines/<%= m.id %>">表示</a>
        <a href="/machines/<%= m.id %>/edit">変更</a></td>
  </tr>
  <% i=i+1 %>
  <% end -%>
</table>
<%= button_to "新規作成", machines_new_path ,method: :get %>

app/views/machines/new.html.erb
<h1>Machines#new</h1>
<p>Find me in app/views/machines/new.html.erb</p>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <%= form_for(@machine) do |f| %>
          <%= f.label :number %>
          <%= f.text_field :number, class: 'form-control' %>
          <%= f.label :model_id %>
          <%= f.collection_select :model_id, Model.all, :id, :name,:prompt => "選択してください" %>
          <%= f.label :from %>
          <%= f.text_field :from, class: 'form-control' %>
          <%= f.label :to %>
          <%= f.text_field :to, class: 'form-control' %>
          <%= f.submit "Create my account", class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
  </div>
</div>
<%= button_to "戻る", machines_index_path ,method: :get %>

app/views/machines/show.html.erb
<h1>Machines#show</h1>
<p>Find me in app/views/machines/show.html.erb</p>

<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h3>台番号:<%= @machine.number %></h3>
      <h3>機種名:<%= @machine.model_id %></h3>
      <h3>対象期間開始:<%= @machine.from %></h3>
      <h3>対象期間終了:<%= @machine.to %></h3>
    </section>
  </aside>
</div>

<%= button_to "戻る", machines_index_path ,method: :get %>

app/views/models/edit.html.erb
<h1>Models#edit</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@model) do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.submit "変更", class: "btn btn-primary" %>
    <% end %>
</div>
<%= button_to "戻る", models_index_path ,method: :get %>

app/views/models/index.html.erb
<h1>Models#index</h1>

<table>
  <tr>
    <th width="20">No</th>
    <th width="120">機種名</th>
    <th width="200">作成日時</th>
    <th width="200">更新日時</th>
    <th width="100">処理</th>
  </tr>
  <% i = 1 %>
  <% @model.each do |m| -%>
  <tr>
    <td><a href="/models/<%= m.id %>"><%= i %></a></td>
    <td><%= m.name %></td>
    <td><%= m.created_at %></td>
    <td><%= m.updated_at %></td>
    <td><a href="/models/<%= m.id %>">表示</a>
        <a href="/models/<%= m.id %>/edit">変更</a></td>
  </tr>
  <% i=i+1 %>
  <% end -%>
</table>
<%= button_to "新規作成", models_new_path ,method: :get %>

app/views/models/new.html.erb
<h1>Models#new</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@model) do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
      <%= f.submit "作成", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>
<%= button_to "戻る", models_index_path ,method: :get %>

app/views/models/show.html.erb
<h1>Models#show</h1>

<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h3>ID:<%= @model.id %></h3>
      <h3>機種名:<%= @model.name %></h3>
      <h3>作成日時:<%= @model.created_at %></h3>
      <h3>更新日時:<%= @model.updated_at %></h3>
    </section>
  </aside>
</div>
<%= button_to "戻る", models_index_path ,method: :get %>

app/views/records/edit.html.erb
<h1>Records#edit</h1>
<p>Find me in app/views/records/edit.html.erb</p>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@record) do |f| %>
      <%= f.label :machine_id %>
      <%= f.text_field :machine_id, class: 'form-control' %>
      <br>
      <%= f.label :date %>
      <%= f.date_field :date, class: 'form-control' %>
      <br>
      <%= f.label :big %>
      <%= f.number_field :big, class: 'form-control' %>
      <br>
      <%= f.label :reg %>
      <%= f.number_field :reg, class: 'form-control' %>
      <br>
      <%= f.label :art %>
      <%= f.number_field :art, class: 'form-control' %>
      <br>
      <%= f.label :roll %>
      <%= f.number_field :roll, class: 'form-control' %>
      <br>
      <%= f.label :final_roll %>
      <%= f.number_field :final_roll, class: 'form-control' %>
      <br>
      <%= f.submit "変更", class: "btn btn-primary" %>
    <% end %>
</div>

<%= button_to "戻る", records_index_path ,method: :get %>

app/views/records/index.html.erb
<h1>Records#index</h1>
<p>Find me in app/views/records/index.html.erb</p>
<% day = Time.now.strftime("%Y-%m-%d") %>
<%= form_tag('/records',:method => :get) do %>
  <%= date_field 'sel_day','day',class: 'form-control' %>
  <%= submit_tag '検索' %>
<% end %>

<table>
  <tr>
    <th width="20">No</th>
    <th width="120">台番号</th>
    <th width="100">日付</th>
    <th width="50">Big</th>
    <th width="50">Reg</th>
    <th width="200">総回転数</th>
    <th width="100">終了回転数</th>
    <th width="50">辛口</th>
    <th width="50">普通</th>
    <th width="50">甘口</th>
  </tr>
  <% i = 1 %>
  <% @record.each do |m| -%>
  <tr>
    <td><a href="/records/<%= m.id %>"><%= i %></a></td>
    <td><%= m.machine_id %></td>
    <td><%= m.date %></td>
    <td><%= m.big %></td>
    <td><%= m.reg %></td>
    <td><%= m.roll %></td>
    <td><%= m.final_roll %></td>
    <td><%= m.dry %></td>
    <td><%= m.result %></td>
    <td><%= m.sweet %></td>
    <td><a href="/records/<%= m.id %>">表示</a>
        <a href="/records/<%= m.id %>/edit">変更</a></td>
  </tr>
  <% i=i+1 %>
  <% end -%>
</table>
<%= button_to "新規作成", records_new_path ,method: :get %>

app/views/records/new.html.erb
<h1>Records#new</h1>
<p>Find me in app/views/records/new.html.erb</p>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@record) do |f| %>
      <%= f.label :machine_id %>
      <%= f.collection_select :machine_id, Machine.all, :id, :number,:prompt => "選択してください" %>
      <br>
      <%= f.label :date %>
      <%= f.date_field :date, class: 'form-control' %>
      <br>
      <%= f.label :big %>
      <%= f.number_field :big, class: 'form-control' %>
      <br>
      <%= f.label :reg %>
      <%= f.number_field :reg, class: 'form-control' %>
      <br>
      <%= f.label :art %>
      <%= f.number_field :art, class: 'form-control' %>
      <br>
      <%= f.label :roll %>
      <%= f.number_field :roll, class: 'form-control' %>
      <br>
      <%= f.label :final_roll %>
      <%= f.number_field :final_roll, class: 'form-control' %>
      <br>
      <%= f.submit "作成", class: "btn btn-primary" %>
    <% end %>
</div>

<%= button_to "戻る", records_index_path ,method: :get %>

app/views/records/show.html.erb
<h1>Records#show</h1>
<p>Find me in app/views/records/show.html.erb</p>